// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: monitor

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;
lv_event_code_t LV_EVENT_GET_COMP_CHILD;
// SCREEN: ui_Screen1
lv_obj_t * ui_Screen1;
lv_obj_t * ui_progress1;
lv_obj_t * ui_title;
lv_obj_t * ui_percent;
lv_obj_t * ui_eta;
lv_obj_t * ui_settings_btn;
lv_obj_t * ui_settings_icon;

// Settings screen variables
lv_obj_t * ui_Screen_Settings;
lv_obj_t * ui_settings_title;
lv_obj_t * ui_wifi_ssid_label;
lv_obj_t * ui_wifi_ssid_input;
lv_obj_t * ui_wifi_pass_label;
lv_obj_t * ui_wifi_pass_input;
lv_obj_t * ui_printer_ip_label;
lv_obj_t * ui_printer_ip_input;
lv_obj_t * ui_connect_btn;
lv_obj_t * ui_connect_label;
lv_obj_t * ui_back_btn;
lv_obj_t * ui_back_label;
lv_obj_t * ui_status_label;
lv_obj_t * ui_brightness_label;
lv_obj_t * ui_brightness_slider;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen_Settings_screen_init();
    lv_disp_load_scr(ui_Screen1);
}