
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: monitor

#ifndef _MONITOR_UI_H
#define _MONITOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_comp.h"
#include "ui_comp_progress.h"
#include "ui_comp_hook.h"

// EVENTS
extern lv_event_code_t LV_EVENT_GET_COMP_CHILD;

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_progress1;
extern lv_obj_t * ui_title;
extern lv_obj_t * ui_percent;
extern lv_obj_t * ui_eta;
extern lv_obj_t * ui_settings_btn;
extern lv_obj_t * ui_settings_icon;

// SCREEN: ui_Screen_Settings
void ui_Screen_Settings_screen_init(void);
extern lv_obj_t * ui_Screen_Settings;
extern lv_obj_t * ui_settings_title;
extern lv_obj_t * ui_wifi_ssid_label;
extern lv_obj_t * ui_wifi_ssid_input;
extern lv_obj_t * ui_wifi_pass_label;
extern lv_obj_t * ui_wifi_pass_input;
extern lv_obj_t * ui_printer_ip_label;
extern lv_obj_t * ui_printer_ip_input;
extern lv_obj_t * ui_connect_btn;
extern lv_obj_t * ui_connect_label;
extern lv_obj_t * ui_back_btn;
extern lv_obj_t * ui_back_label;
extern lv_obj_t * ui_status_label;
extern lv_obj_t * ui_brightness_label;
extern lv_obj_t * ui_brightness_slider;

// FONTS
LV_FONT_DECLARE(ui_font_Arial_100);
LV_FONT_DECLARE(ui_font_Arial_110);

// IMAGES


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
