// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: monitor

#ifndef _UI_COMP_PROGRESS_H
#define _UI_COMP_PROGRESS_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT progress
#define UI_COMP_PROGRESS_PROGRESS 0
#define _UI_COMP_PROGRESS_NUM 1
lv_obj_t * ui_progress_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
