
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: monitor

#include "ui.h"

// COMPONENT progress

lv_obj_t * ui_progress_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_progress;
    cui_progress = lv_arc_create(comp_parent);
    lv_obj_set_width(cui_progress, 300);
    lv_obj_set_height(cui_progress, 300);
    lv_obj_set_x(cui_progress, 0);
    lv_obj_set_y(cui_progress, 37);
    lv_obj_set_align(cui_progress, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_progress, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(cui_progress, 77);
    lv_arc_set_bg_angles(cui_progress, 135, 45);
    
    // Main arc (background) styling
    lv_obj_set_style_bg_img_tiled(cui_progress, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(cui_progress, lv_color_hex(0x4B4B4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(cui_progress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(cui_progress, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Indicator (progress) styling
    lv_obj_set_style_arc_color(cui_progress, lv_color_hex(0x14D132), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(cui_progress, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(cui_progress, 30, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Knob styling (make it invisible)
    lv_obj_set_style_bg_color(cui_progress, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_progress, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PROGRESS_NUM);
    children[UI_COMP_PROGRESS_PROGRESS] = cui_progress;
    lv_obj_add_event_cb(cui_progress, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_progress, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_progress_create_hook(cui_progress);
    return cui_progress;
}
