
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: monitor

#include "ui.h"
#include "ui_events.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create progress component
    ui_progress1 = ui_progress_create(ui_Screen1);
    lv_obj_set_x(ui_progress1, 0);
    lv_obj_set_y(ui_progress1, 37);
    lv_obj_set_align(ui_progress1, LV_ALIGN_CENTER);

    // Title label (H2D)
    ui_title = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_title, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_title, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_title, 0);
    lv_obj_set_y(ui_title, -138);
    lv_obj_set_align(ui_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_title, "H2D");
    lv_obj_set_style_text_color(ui_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_title, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Percentage label (77)
    ui_percent = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_percent, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_percent, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_percent, 0);
    lv_obj_set_y(ui_percent, 38);
    lv_obj_set_align(ui_percent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_percent, "77");
    lv_obj_set_style_text_color(ui_percent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_percent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_percent, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_percent, &ui_font_Arial_110, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ETA label (11h 22min)
    ui_eta = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_eta, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_eta, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_eta, 0);
    lv_obj_set_y(ui_eta, 138);
    lv_obj_set_align(ui_eta, LV_ALIGN_CENTER);
    lv_label_set_text(ui_eta, "11h 22min");
    lv_obj_set_style_text_color(ui_eta, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_eta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_eta, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Settings gear button
    ui_settings_btn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_settings_btn, 30);
    lv_obj_set_height(ui_settings_btn, 30);
    lv_obj_set_x(ui_settings_btn, -7);
    lv_obj_set_y(ui_settings_btn, 7);
    lv_obj_set_align(ui_settings_btn, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_style_bg_color(ui_settings_btn, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_settings_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_settings_btn, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Gear icon (using label with gear symbol for now)
    ui_settings_icon = lv_label_create(ui_settings_btn);
    lv_obj_set_width(ui_settings_icon, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_settings_icon, LV_SIZE_CONTENT);
    lv_obj_center(ui_settings_icon);
    lv_label_set_text(ui_settings_icon, LV_SYMBOL_SETTINGS);
    lv_obj_set_style_text_color(ui_settings_icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_icon, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Add event handler to settings button
    lv_obj_add_event_cb(ui_settings_btn, ui_event_settings_btn, LV_EVENT_ALL, NULL);
}
