
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: monitor

#include "ui.h"
#include "ui_events.h"

void ui_Screen_Settings_screen_init(void)
{
    ui_Screen_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Settings, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Screen_Settings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_Settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Settings title
    ui_settings_title = lv_label_create(ui_Screen_Settings);
    lv_obj_set_width(ui_settings_title, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_settings_title, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_settings_title, 0);
    lv_obj_set_y(ui_settings_title, -180);
    lv_obj_set_align(ui_settings_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settings_title, "Settings");
    lv_obj_set_style_text_color(ui_settings_title, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_settings_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_settings_title, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    // WiFi SSID label
    ui_wifi_ssid_label = lv_label_create(ui_Screen_Settings);
    lv_obj_set_width(ui_wifi_ssid_label, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_wifi_ssid_label, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_wifi_ssid_label, -100);
    lv_obj_set_y(ui_wifi_ssid_label, -120);
    lv_obj_set_align(ui_wifi_ssid_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifi_ssid_label, "WiFi SSID:");
    lv_obj_set_style_text_color(ui_wifi_ssid_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifi_ssid_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    // WiFi SSID input
    ui_wifi_ssid_input = lv_textarea_create(ui_Screen_Settings);
    lv_obj_set_width(ui_wifi_ssid_input, 200);
    lv_obj_set_height(ui_wifi_ssid_input, 40);
    lv_obj_set_x(ui_wifi_ssid_input, 50);
    lv_obj_set_y(ui_wifi_ssid_input, -120);
    lv_obj_set_align(ui_wifi_ssid_input, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_wifi_ssid_input, "Enter WiFi name");
    lv_textarea_set_one_line(ui_wifi_ssid_input, true);

    // WiFi Password label
    ui_wifi_pass_label = lv_label_create(ui_Screen_Settings);
    lv_obj_set_width(ui_wifi_pass_label, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_wifi_pass_label, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_wifi_pass_label, -100);
    lv_obj_set_y(ui_wifi_pass_label, -70);
    lv_obj_set_align(ui_wifi_pass_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifi_pass_label, "WiFi Password:");
    lv_obj_set_style_text_color(ui_wifi_pass_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifi_pass_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    // WiFi Password input
    ui_wifi_pass_input = lv_textarea_create(ui_Screen_Settings);
    lv_obj_set_width(ui_wifi_pass_input, 200);
    lv_obj_set_height(ui_wifi_pass_input, 40);
    lv_obj_set_x(ui_wifi_pass_input, 50);
    lv_obj_set_y(ui_wifi_pass_input, -70);
    lv_obj_set_align(ui_wifi_pass_input, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_wifi_pass_input, "Enter password");
    lv_textarea_set_one_line(ui_wifi_pass_input, true);
    lv_textarea_set_password_mode(ui_wifi_pass_input, true);

    // Printer IP label
    ui_printer_ip_label = lv_label_create(ui_Screen_Settings);
    lv_obj_set_width(ui_printer_ip_label, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_printer_ip_label, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_printer_ip_label, -100);
    lv_obj_set_y(ui_printer_ip_label, -20);
    lv_obj_set_align(ui_printer_ip_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_printer_ip_label, "Printer IP:");
    lv_obj_set_style_text_color(ui_printer_ip_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_printer_ip_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Printer IP input
    ui_printer_ip_input = lv_textarea_create(ui_Screen_Settings);
    lv_obj_set_width(ui_printer_ip_input, 200);
    lv_obj_set_height(ui_printer_ip_input, 40);
    lv_obj_set_x(ui_printer_ip_input, 50);
    lv_obj_set_y(ui_printer_ip_input, -20);
    lv_obj_set_align(ui_printer_ip_input, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_printer_ip_input, "192.168.1.100");
    lv_textarea_set_one_line(ui_printer_ip_input, true);

    // Brightness label
    ui_brightness_label = lv_label_create(ui_Screen_Settings);
    lv_obj_set_width(ui_brightness_label, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_brightness_label, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_brightness_label, -100);
    lv_obj_set_y(ui_brightness_label, 30);
    lv_obj_set_align(ui_brightness_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_brightness_label, "Brightness:");
    lv_obj_set_style_text_color(ui_brightness_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_brightness_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Brightness slider
    ui_brightness_slider = lv_slider_create(ui_Screen_Settings);
    lv_obj_set_width(ui_brightness_slider, 200);
    lv_obj_set_height(ui_brightness_slider, 20);
    lv_obj_set_x(ui_brightness_slider, 50);
    lv_obj_set_y(ui_brightness_slider, 30);
    lv_obj_set_align(ui_brightness_slider, LV_ALIGN_CENTER);
    lv_slider_set_range(ui_brightness_slider, 10, 100);
    lv_slider_set_value(ui_brightness_slider, 80, LV_ANIM_OFF);
    lv_obj_set_style_bg_color(ui_brightness_slider, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_brightness_slider, lv_color_hex(0x14D132), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_brightness_slider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);

    // Connect button
    ui_connect_btn = lv_btn_create(ui_Screen_Settings);
    lv_obj_set_width(ui_connect_btn, 120);
    lv_obj_set_height(ui_connect_btn, 50);
    lv_obj_set_x(ui_connect_btn, -50);
    lv_obj_set_y(ui_connect_btn, 120);
    lv_obj_set_align(ui_connect_btn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_connect_btn, lv_color_hex(0x14D132), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_connect_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_connect_btn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_connect_label = lv_label_create(ui_connect_btn);
    lv_obj_center(ui_connect_label);
    lv_label_set_text(ui_connect_label, "Connect");
    lv_obj_set_style_text_color(ui_connect_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_connect_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Back button
    ui_back_btn = lv_btn_create(ui_Screen_Settings);
    lv_obj_set_width(ui_back_btn, 120);
    lv_obj_set_height(ui_back_btn, 50);
    lv_obj_set_x(ui_back_btn, 80);
    lv_obj_set_y(ui_back_btn, 120);
    lv_obj_set_align(ui_back_btn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_back_btn, lv_color_hex(0x666666), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_back_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_back_btn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_back_label = lv_label_create(ui_back_btn);
    lv_obj_center(ui_back_label);
    lv_label_set_text(ui_back_label, "Back");
    lv_obj_set_style_text_color(ui_back_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_back_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Status label
    ui_status_label = lv_label_create(ui_Screen_Settings);
    lv_obj_set_width(ui_status_label, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_status_label, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_status_label, 0);
    lv_obj_set_y(ui_status_label, 180);
    lv_obj_set_align(ui_status_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_status_label, "Status: Not connected");
    lv_obj_set_style_text_color(ui_status_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_status_label, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Add event handlers
    lv_obj_add_event_cb(ui_connect_btn, ui_event_connect_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_back_btn, ui_event_back_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_brightness_slider, ui_event_brightness_slider, LV_EVENT_ALL, NULL);
}
